FROM node:16-alpine as client

WORKDIR /client

COPY ./client .

RUN yarn install

RUN yarn build

RUN rm -rf node_modules
RUN rm -rf src

FROM nginx:1.23.4-alpine

COPY --from=client /client/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
