FROM python:3.9-slim-buster

WORKDIR /server

COPY ./server/requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY ./server .
COPY .env .

EXPOSE 8080

CMD ["flask", "run", "--host", "0.0.0.0", "--port", "8080"]